### ISSUE TITLE
[BUG] Unable to open window

### ISSUE THREAD

**Issue by Grygon** [ardittristan/VTTExternalActorViewer#1]
On clicking "Get id" nothing opens.

Running Foundry via Firefox.
Also using a _whole bunch_ of modules, but I think the important one here is Tidy5e Sheet

Relevant portion from actorAPI:
`"GkeLMYNsZKwi5QUI":{"_id":"GkeLMYNsZKwi5QUI","name":"Ghurlsall Zarr","permission":{"default":0,"YlgcTXti0BqoRR4Z":3,"OzQwY59yMsYztlri":3},"type":"character","data":...`

I don't think the template location matches in-console lines up with where it actually is, but I could be wrong:
![image](https://user-images.githubusercontent.com/647846/89239415-b8412100-d5be-11ea-97e2-a40552cf096e.png)

(loading that directly works:)
![image](https://user-images.githubusercontent.com/647846/89239461-deff5780-d5be-11ea-93d1-8f42a7ad1267.png)

From the console:
```
Foundry VTT | Rendering CopyPopupApplication foundry.js:3855:15
Foundry VTT | Retrieved and compiled template getRunningScript/<@modules/externalactor/templates/copyPopup.html foundry.js:5224:16
Error: An error occurred while rendering CopyPopupApplication 87: No data was returned from template getRunningScript/<@modules/externalactor/templates/copyPopup.html
    _renderInner https://url/scripts/foundry.js:3998
    _render https://url/scripts/foundry.js:3868
    render https://url/scripts/foundry.js:3831
    <anonymous> https://url/modules/externalactor/actorviewer.js:53
    jQuery 2
foundry.js:3833:14
    render https://url/scripts/foundry.js:3833
    (Async: promise callback)
    render https://url/scripts/foundry.js:3831
    <anonymous> https://url/modules/externalactor/actorviewer.js:53
```

**Comment by ardittristan** [comment]
should be fixed with 1.0.2
