### ISSUE TITLE
Error 1003 Direct IP access not allowed

### ISSUE THREAD

**Issue by Aswabor** [ardittristan/VTTExternalActorViewer#13]
I can not get it to work, it always shows "URL not found" and in the console i get the following error:
`Failed to load resource: the server responded with a status of 403 ()`
followed by this link:https://cors-anywhere.ardittristan.workers.dev/corsproxy/?apiurl=http://IP/actorAPI/world-actors.json
when i click it i get a page that says: Error 1003 Direct IP access not allowed
i can open the actor.json file on its one just fine through: http://IP/actorAPI/world-actors.json

thanks Aswabor

**Comment by ardittristan** [comment]
The proxy that is used for accessing the data on foundry (which isn't directly possible because of internet security protocols) doesn't allow for direct ips. You could use a service like https://www.noip.com (which you can use for free, with a manual action once a month) to link a dns to your ip.

**Comment by Aswabor** [comment]
thanks i set up noip, but now it fails to retrieve data after about 30 seconds. 
with: net::ERR_EMPTY_RESPONSE

**Comment by ardittristan** [comment]
Could you maybe dm me the address on discord `ardittristan#0001` so I can test?

**Comment by ardittristan** [comment]
fixed by only applying code in proxy for #8 when https instead of also running on http requests, which broke
