### ISSUE TITLE
5e characters saves and skills have NaN

### ISSUE THREAD

**Issue by crimsonknave** [ardittristan/VTTExternalActorViewer#15]
When viewing a character sheet their saving throws and proficiencies are `NaN` instead of the actual value. I'm assuming this is because they're a string when a number is expected. I'm using the ddb-importer to import characters. I did notice that one of my NPCs still has `NaN` for saving throws and skills, except for the single skill they're proficient with, so it can work, just not all the time.

![image](https://user-images.githubusercontent.com/352979/146210038-17e39544-76e7-490b-b8a2-e5542cdf7588.png)

**Comment by ardittristan** [comment]
could you maybe send me a json file that shows the NaN when you try to view it? then I can see how the data gets noted down so I can make a workaround for it! If you don't want to send it here you can also send it on discord `ardittristan#0001`

**Comment by crimsonknave** [comment]
The json file is massive, even a single entry so I don't think it'll be easy to upload. But, I dug in a bit and I when I see `NaN` the skill or attribute doesn't have the `prof`, `bonus` or `total` fields, both `NaN` and working have `value`, `ability`, `bonuses` (and the nested fields), `total` and `passive` Total and Passive are both `null` when it's `NaN`.

**Comment by ardittristan** [comment]
more data is missing than just the total and passive it seems. I think having the json would be very very handy. You can probably zip it up, which generally makes the size a loooot smaller since it's a lot of repeating text!

**Comment by crimsonknave** [comment]
[nan.tar.gz](https://github.com/ardittristan/VTTExternalActorViewer/files/7735979/nan.tar.gz)
Fair enough, here it is. `DUm9Alemp412gB8P` has mostly `NaN`, but at least one that works.

**Comment by ardittristan** [comment]
I've updated the site, could you retry?

**Comment by crimsonknave** [comment]
Looks good now, thanks!
