### ISSUE TITLE
Can't get it to work. Maybe a Forge issue?

### ISSUE THREAD

**Issue by baileywick** [ardittristan/VTTExternalActorViewer#2]
I host my game on Forge, Not sure if I'm doing something wrong, but it just says "URL Not Found" when i try to open the actor sheet up from the URL.

**Comment by baileywick** [comment]
Saw the update that you tried to get it working on Forge. But I just tried it and I still get the "URL Not Found" error. Not sure I'm doing something wrong. Let me know if I can help in any way.

**Comment by baileywick** [comment]
Almost there! The sheet will load but the background won't load to make it legible. 

![image](https://user-images.githubusercontent.com/14203358/89960161-0b385b00-dbf3-11ea-8536-bacf2b1797cf.png)

**Comment by ardittristan** [comment]
sorry for the late reply. apparently notifications for the repo were off...

this is indeed an issue with forge. since it has it's assets split over multiple locations.
if your game is on public and not private you can try `yoururl.forge-vtt.com/actorAPI/...`

**Comment by ardittristan** [comment]
@Puddinglord can you maybe provide more information about how you have your foundry setup?

**Comment by Puddinglord** [comment]
@ardittristan Yes I am running Foundry locally on a Raspberry Pi. I have the port forwarded so my other players can connect from their own devices outside of my network.

**Comment by baileywick** [comment]
Indeed, that worked! I can now see the character sheet from my Forge
instance. I can't do anything to actually interact with that sheet other
than change tabs, but I'm assuming that's just the limitations of the
module's functionality right now.
