### ISSUE TITLE
Changing sheet assigned to token leads to degraded server performance

### ISSUE THREAD

**Issue by dstein766** [ardittristan/VTTExternalActorViewer#4]
Trying to use External Actor Viewer and have found a repeatable sequence that appears to seriously degrade the server's performance.
Windows 10 1909
Foundy 0.6.6
DND5e 0.96
External Actor Viewer 1.0.8
NO OTHER MODULES ENABLED

1) Open any token that has a character sheet.  (Doesn't matter whether PC character sheet or NPC character sheet)
2) Click on the Sheet option to change to a different character sheet - but do NOT make any changes.  (In my test I've disabled all other sheets, so the only choices in the dropdown are Default and the explicitly named built-in sheet).
3) Click "Save Sheet Configuration" (having made no changes).  So far, all is OK.
4) Click on the Sheet option and explicitly select the "dnd5e.ActorSheet5eCharacter".  Click "Save Sheet Configuration".  Sheet closes...but the Sheet Configuration dialog remains open on-screen instead of closing.  (Usually this is apparent immediately.  One time the dialog closed as expected the 1st time but then remained on screen on my second attempt.)  Clicking on the X shrinks down to title-bar sized window of the Sheet Configuration form, but doesn't dismiss the form.  The form will reopen if I 2x click the minimized header.

At this point, the stability/performance of the server appears to be compromised.  To see this, go back to Foundry Settings --> Manage Modules and click Save Module Settings (without making any changes).  Expected behavior is a full screen refresh within a few seconds.  The observed behavior is that the screen goes black, showing only the Foundry anvil in the upper left for a significant period of time (>30 seconds?  didn't time it...).  At this point ALL subsequent refresh activities do the same thing.  So if you repeat the Save Module Settings action the slow response remains until the server is recycled.

**Comment by ardittristan** [comment]
I am not able to reproduce this issue on my end, are there any errors being shown in the console? (ctrl + shift + i)

**Comment by dstein766** [comment]
I'm still trying to characterize this.  Can recreate 100% of the time 
with the process previously documented and still happens with most 
recent release from 1-2 days ago.  Have ruled out browser extensions and 
other Foundry modules.  I am running the node.js version as a service 
under Windows 10, which I mention only because I suspect that's "not 
usual".

Until/unless I can get you good data I'll assume I've got some weird 
local issue happening.

------ Original Message ------

**Comment by ardittristan** [comment]
The main thing that confuses me is that i only do one thing with the actual sheet. Which is adding the button to the top.

**Comment by dstein766** [comment]
These are initial observations when looking at the console messages 
live.

1) Enable the module
2) Foundry refreshes, and then console begins to fill with seemingly 
endless stream of messages like this:
 >(5) [Actor5e, {...}, {...}, {...}, "1U2E14MAMIbWTyUa"]      
foundry.js:2194
DEBUG | Calling updateOwnedItem hook with args:      foundry.js:2193

    This has been going on for >5 minutes (so far).  There's about 8000 
of them so far.

3) Finally gave up and disabled the module again---> Foundry 
refreshed...but console printed the 1st ~8-10 lines (the lines where 
"Foundry" is spelled out in line graphics...and then hung for about 3 
minutes before finally finishing refresh.  Haven't characterized whether 
it is performant now, but prior experience suggests I probably need to 
bounce the service to get back to full performance.

4) All modules disabled except yours.  Opened PC token.  Selected 
"Sheet".  Modified current sheet from Default to 
dnd5e.ActorSeet5eCharacter (which is the only choice).  Click Save --> 
NOTHING happening in the console.  No updates of any kind.  (I typed "/r 
d20" in Chat and did get a console update, so things are not totally 
dead.)

I haven't yet found whether there's some useful info that appears prior 
to the spew of lines described in #2, but that spew is only happening 
with ExternalActorViewer enabled.  (I'm basically learning to use the 
console as just-in-time learning, so if there's something specific you'd 
suggest I look for I'm all ears.)

------ Original Message ------

**Comment by dstein766** [comment]
Further observations:  A normal refresh (without EAV enabled) generates about 1097 console messages, including 6 - apparently harmless - errors.  A refresh w/EAV enabled is generating many thousands of console message, but only 4 errors.  The first 2200 or so messages appear within seconds of refresh, the rest trickle in at the rate of approx 8-10/second from there.)  From this I conclude that init is never actually completing, as whatever generates the last two errors apparently isn't even getting executed.  

Here's an extract of the console w/EAV enabled, showing the spewage:
![image](https://user-images.githubusercontent.com/24942951/92428655-8d5d6600-f144-11ea-84d1-b5de0e39dda5.png)

I expanded a few random nodes just to confirm that different objects are apparently getting touched each time.  I'm just going to leave this running for at least 30 minutes to see if it ever stops spewing and eventually prints the two "missing" errors.

FWIW: searching the console for "xternal" yields only 1 match w/EAV enabled ("Foundry VTT | Loaded localization file modules/externalactor/lang/en.json").  None of the error messages have any obvious relationship to EAV.

**Comment by dstein766** [comment]
OK.  I left it running with EAV enabled and the console still spewing messages.  It eventually stopped spewing.  At that point, I was able to open up a PC sheet and modify the sheet type w/o everything hanging.  So whatever is causing the message spewing also seems to be causing the problem I'm reporting.  Disabling EAV and then re-enabling it still results in the same console spew again.   Bottom line: If I wait out the spewage, its working...but the spewage is lasting anywhere from 5-15 minutes, during which performance of Foundry is serious compromised.

**Comment by ardittristan** [comment]
hm, I am adding a flag to items on game launch, this could be the cause. Though I don't know why it makes your system lag so much. I'll add a setting to disable the flag adding, but that will mean that some data won't be put in the external viewer (class label, item label)

**Comment by ardittristan** [comment]
can you try with this [manifest](https://github.com/ardittristan/VTTExternalActorViewer/raw/dev/module.json) and enable the performance setting in the settings?

**Comment by dstein766** [comment]
Unable to figure out how to "enable the performance setting"?

Deinstalled current version, re-installed from your manifest link.  
Enable in Manage Modules.  On auto-refresh following exit of Manage 
Modules, console spews the "calling updateOwnedItem hook with args:" 
messages as before.  Wait for it to stop spewing (about 5 minutes).  Go 
into Configure Settings...but there's no entry for External Actor 
Viewer?

Did a very uneducated view of the various *.js files hoping to find 
something that I could potentially hard-code, but nothing jumped out.

------ Original Message ------

**Comment by ardittristan** [comment]
can you check which version the module is? maybe I didn't fully set up the dev manifest right. it should be 0.0.10

**Comment by dstein766** [comment]
It is still showing 0.0.9

------ Original Message ------

**Comment by ardittristan** [comment]
it should work now, I updated the manifest. same link

**Comment by dstein766** [comment]
So that manifest does expose the setting choice, so after waiting out 
the spew from the initial enablement I turned on Performance Mode and 
reloaded the session.  I'm not seeing any change in behavior.  The # of 
messages getting spewed is unchanged, so it doesn't appear to be 
applying a "lighter touch".

I don't know what items get passed to updateOwnedItem at startup...but 
the sheer number of messages is larger than I'd expect.  I've got about 
3000 info message, and since each call appears to generate 2 messages - 
one the DEBUG message, the other the logging of the args being passed - 
this suggests that the spew represents ~1500 calls to updateOwnedItem.  
I've got a total of 41 Actors in the Actor sidebar.  It is possible that 
between all their features, inventory, and spellbook nodes they MIGHT 
have ~1500 entries between them.  Would that be the source of the ~1500 
calls?  If any of features, inventory, and/or spellbook entries would 
NOT generate a call to updateOwnedItem then I'm not sure what would 
result in 1500 calls.  Is it possible that there's some kind of looping 
bug that's causing too many recursive calls to updateOwnedItem??

------ Original Message ------

**Comment by ardittristan** [comment]
I updated the dev version to include more in performance mode, could you retry?
What I am doing which I think is causing this is this:
```js
if (game.user.isGM) {
  actor.setFlag("externalactor", "disableExperience", game.settings.get("dnd5e", "disableExperienceTracking"));
  actor.setFlag("externalactor", "currencyWeight", game.settings.get("dnd5e", "currencyWeight"));
  actor.setFlag("externalactor", "classLabels", actor.itemTypes.class.map(c => c.name).join(", "));
}

actor.items.forEach(item => {
  if (game.user.isGM) {
    item.setFlag("externalactor", "labels", item.labels);
  }
  items.push(item.data);
});
```
though that doesn't cause any slowdown for me.

**Comment by dstein766** [comment]
Installed x.x.11.  Upon return to game (with EAV already enabled and 
Performance Mode already checked from prior install) the # of msgs in 
the console is now about 600 for a refresh instead of the 3600 of prior 
invocations.  So whatever change you just made definitely addressed the 
spewage.

Still begs the question of why it happens for me and not you (or 
others)?  I'll continue to poke around and try to see if I can figure 
that out.  So far, though, I seem to have ruled out Chrome extensions, 
other Foundry modules, and system capabilities.  (I'm running on a new 
Dell laptop with an Intel i10 processor, so I'm about as full-powered 
and modern as can be expected....although I just now remembered that my 
foundrydata tree is on a "slow" USB drive and not a "fast" 
SSD...wondering if that's a contributor?  I'm unlikely to change that 
since SSD is a limited resource for me and foundry doesn't qualify as 
something that I'm going to grant SSD space to).

I'm going to revisit my testing methodology to include forcibly bouncing 
the service every time I toggle the state of modules.  I suppose it is 
possible for this to be a module interaction issue that's really 
sensitive to state, and bouncing the server would ensure that I always 
have the same starting state.  My earlier methodology didn't have that 
guaranteed starting state each time.

For now, I'd be inclined to consider this "solved" - even though I 
recognize that we've just really kludged things - until such time as 
someone else reports similar issues and/or I come up with more definite 
data for you.  I've got a special-build that's "working" - and if I 
don't like the way it works I can remove the special config setting and 
resign myself to fully working (at the cost of performance).

Thanks for the responsiveness to my reports!

------ Original Message ------

**Comment by ardittristan** [comment]
I'll push the setting to master if anyone else wants it! it might have something to do with the amount of read/writes it does to the foundry actor database. (though I don't really see another way of adding this data to the json). Personally I run my test server on a 5400rpm harddrive which also isn't the fasteds. But flash memory is way slower generally.
