### ISSUE TITLE
Actor URL appears invalid after adding Self-Signed or non fullchain Certificates to Foundry.

### ISSUE THREAD

**Issue by Kantharr** [ardittristan/VTTExternalActorViewer#8]
The External Actor Viewer module was working for my players before I added Self-Signed Certificates to Foundry to make the access more secure. Before adding the certificate the actor's URL was:

http://{ip-address}:30000/actorAPI/{world-name}-actors.json{actorID}

But once I added  the certificate the URL were changed to:

https://{ip-address}:30000{actorID}

Is this working as intended or is it supposed to add the /actorPI/{world-name}-actors.json before the actorID?

**Comment by ardittristan** [comment]
First url is correct, 2nd isn't. Is there any errors in the console?

Though i don't know if the site will work at all with self signed https since it goes through a proxy to circumvent CORS. If http isn't blocked i recommend using that for the site. Or getting a letsencrypt certificate.

**Comment by Kantharr** [comment]
The following error was returned for the 2nd link:

![139889219_443822146775573_1610058092276963383_n](https://user-images.githubusercontent.com/7611895/104867907-8f5fde80-5907-11eb-979b-431ebb25f5f8.jpg)

So the URL are now correct, which I'm thinking it was from turning on the Optimize Static Files setting.

I will try the letsencrypt certificate first and if that doesn't work I'll try looking up how to set a proxy.

**Comment by Kantharr** [comment]
The following error was returned for the 2nd link:

![139889219_443822146775573_1610058092276963383_n](https://user-images.githubusercontent.com/7611895/104868126-2c227c00-5908-11eb-966a-0aae2009ed20.jpg)

So the URL are now correct, which I'm thinking it was from turning on the Optimize Static Files setting.

I will try the letsencrypt certificate first and if that doesn't work I'll try looking up how to set a proxy.

**Comment by gohma231** [comment]
I'm having the same issue and used certbot (LetsEncrypt) to have a signed and trusted certificate. When I enable SSL, I receive the same "URL not found" screen.

![image](https://user-images.githubusercontent.com/4106435/104988837-1768e580-59e7-11eb-98ad-29f1d4bd24b6.png)

Clicking the link opens this page: 
![image](https://user-images.githubusercontent.com/4106435/104988940-55660980-59e7-11eb-975d-907a7f3c64c3.png)


Any ideas?

**Comment by ardittristan** [comment]
The 2nd image is expected, since the proxy only works with api requests and not directly in the browser.

Is there any error in the foundry console maybe?

**Comment by gohma231** [comment]
That is interesting! I can see the whole json file and can ctrl +f to find the actor ID. The console does not appear to have anything relevant. 

The external viewer application does stay on 'retrieving data' for about 5 seconds before switching to 'URL not found'. 

Any ideas? Is there anything I can provide to assist?

**Comment by ardittristan** [comment]
if you don't mind you could dm me the file address on discord (ardittristan#0001) so I can try to debug as well. otherwise, maybe try with a different actor?

**Comment by gohma231** [comment]
I've tried a few different actors (including making new ones). I don't actually know your discord tag otherwise I would have DMed you.

**Comment by ardittristan** [comment]
Oh, it turned my discord tag into a link... `ardittristan#0001`

**Comment by gohma231** [comment]
To anyone that may encounter this issue:

When you use certbot, your `options.json` sslCert needs to use `fullchain.pem`. I was using `cert.pem` which was causing the error.
