### ISSUE TITLE
Support absolute actor image URLs

### ISSUE THREAD

**Issue by sneat** [ardittristan/VTTExternalActorViewer#9]
Currently the viewer assumes that the actor image URL is a relative URL and doesn't support absolute URLS (e.g. those starting with `https://`). Could you add something like this?

```js
try {
  new window.URL(actor.img);
  // the image is an absolute URL and shouldn't have the site domain prepended to it.
} catch (e) {
  // the image is a relative URL, do what you currently normally do.
}
```

**Comment by ardittristan** [comment]
should be added with https://github.com/ardittristan/VTTExternalActorSites
